LAUNCH_COL_NAMES = {
    '#Launch_Tag': 'launch_ID',
    'Launch_JD': 'Julian_Date',
    'Launch_Date': 'launch_date',
    'LV_Type': 'rocket_type',
    'Variant': 'rocket_variant',
    'Flight_ID': 'flight_ID',
    'Flight': 'payload',
    'Mission': 'mission_name',
    'FlightCode': 'flight_code',
    'Platform': 'launch_platform',
    'Launch_Site': 'launch_site',
    'Launch_Pad': 'launch_pad',
    'Ascent_Site': 'ascent_site',
    'Ascent_Pad': 'ascent_pad',
    'Apogee': 'apogee_(km)',
    'Apoflag': 'apogee_flag',
    'Range': 'range_(km)',
    'RangeFlag': 'range_flag',
    'Dest': 'destination',
    'OrbPay': 'payload_(t)',
    'Agency': 'launch_agency',
    'Launch_Code': 'launch_code',
    'Group': 'leading_org',
    'Category': 'flight_type',
    'LTCite': 'time_reference',
    'Cite': 'additional_ref',
    'Notes': 'notes'
}
SATCAT_COL_NAMES = {
    '#JCAT': 'JCAT_number',
    'Satcat': 'Sat_catalog',
    'Piece': 'piece_ID',
    'Type': 'object_type',
    'Name': 'object_name',
    'PLName': 'payload_name',
    'LDate': 'launch_date',
    'Parent': 'parent_object',
    'SDate': 'status_date',
    'Primary': 'primary',
    'DDate': 'phase_end_date',
    'Status': 'status',
    'Dest': 'destination',
    'Owner': 'object_owner',
    'State': 'object_state',
    'Manufacturer': 'manufacturer',
    'Bus': 'bus',
    'Motor': 'motor',
    'Mass': 'mass',
    'MassFlag': 'mass_flag',
    'DryMass': 'dry_mass',
    'DryFlag': 'dry_flag',
    'TotMass': 'total_mass',
    'TotFlag': 'total_flag',
    'Length': 'length',
    'LFlag': 'length_flag',
    'Diameter': 'diameter',
    'DFlag': 'diameter_flag',
    'Span': 'span',
    'SpanFlag': 'span_flag',
    'Shape': 'shape',
    'ODate': 'orbit_date',
    'Perigee': 'perigee_km',
    'PF': 'perigee_flag',
    'Apogee': 'apogee_km',
    'AF': 'apogee_flag',
    'Inc': 'inclination',
    'IF': 'incl_flag',
    'OpOrbit': 'oper_orbit',
    'OQUAL': 'orbit_quality',
    'AltNames': 'alternate_names'
}
CELESTRAK_SATCAT_COL_NAMES = {
    'OBJECT_NAME': 'satellite_name',
    'OBJECT_ID': 'piece_ID',
    'NORAD_CAT_ID': 'norad_id',
    'OBJECT_TYPE': 'object_type',
    'OPS_STATUS_CODE': 'ops_status',
    'OWNER': 'owner',
    'LAUNCH_DATE': 'launch_date',
    'LAUNCH_SITE': 'launch_site',
    'DECAY_DATE': 'decay_date',
    'PERIOD': 'orbital_period',
    'INCLINATION': 'inclination_deg',
    'APOGEE': 'apogee_km',
    'PERIGEE': 'perigee_km',
    'RCS': 'radar_cross_sec',
    'DATA_STATUS_CODE': 'data_status',
    'ORBIT_CENTER': 'orbit_center',
    'ORBIT_TYPE': 'orbit_type'
}
CURRENTCAT_COL_NAMES = {
    '#JCAT': 'JCAT_number',
    'DeepCat': 'DeepSpace_cat',
    'Satcat': 'Sat_catalog',
    'Piece': 'piece_ID',
    'Active': 'active_status',
    'Type': 'object_type',
    'Name': 'object_name',
    'LDate': 'launch_date',
    'Parent': 'parent_object',
    'Owner': 'object_owner',
    'State': 'object_state',
    'SDate': 'status_date',
    'ExpandedStatus': 'exp_status',
    'DDate': 'phase_end_date',
    'ODate': 'orbit_date',
    'Period': 'orbital_period',
    'Perigee': 'perigee_km',
    'PF': 'perigee_flag',
    'Apogee': 'apogee_km',
    'AF': 'apogee_flag',
    'Inc': 'inclination',
    'IF': 'incl_flag',
    'OpOrbit': 'oper_orbit'
}
LAUNCHLOG_COL_NAMES = {
    '#Launch_Tag': 'launch_ID',
    'Launch_Date': 'launch_date',
    'Piece': 'piece_ID',
    'Type': 'object_type',
    'Name': 'object_name',
    'PLName': 'payload_name',
    'JCAT': 'JCAT_number',
    'SatOwner': 'sat_owner',
    'SatState': 'sat_state',
    'LV_Type': 'rocket_type',
    'Flight_ID': 'flight_ID',
    'Platform': 'launch_platform',
    'Launch_Site': 'launch_site',
    'Launch_Pad': 'launch_pad',
    'Ascent_Site': 'ascent_site',
    'Ascent_Pad': 'ascent_pad',
    'Agency': 'launch_agency',
    'LVState': 'LV_state',
    'Launch_Code': 'launch_code',
    'LTCite': 'time_ref'
}
ORGS_COL_NAMES = {
    '#Code': 'org_code',
    'UCode': 'UN_code',
    'StateCode': 'state_code',
    'Type': 'org_type',
    'Class': 'org_class',
    'TStart': 'start_time',
    'TStop': 'stop_time',
    'ShortName': 'short_name',
    'Name': 'org_name',
    'Location': 'org_location',
    'Longitude': 'longitude',
    'Latitude': 'latitude',
    'Error': 'location_error',
    'Parent': 'parent_org',
    'ShortEName': 'short_EN_name',
    'EName': 'EN_name',
    'UName': 'UN_name'
}
PSATCAT_COL_NAMES = {
    '#JCAT': 'JCAT_number',
    'Piece': 'piece_ID',
    'Name': 'object_name',
    'LDate': 'launch_date',
    'TLast': 'last_time',
    'TOp': 'oper_time',
    'TDate': 'date',
    'TF': 'time_flag',
    'Program': 'program',
    'Plane': 'plane',
    'Att': 'attitude',
    'Mvr': 'maneuver',
    'Class': 'class',
    'Category': 'category',
    'UNState': 'owner_state',
    'UNReg': 'UN_reg',
    'UNPeriod': 'period_km',
    'UNPerigee': 'perigee_km',
    'UNApogee': 'apogee_km',
    'UNInc': 'inclination',
    'Result': 'result',
    'Control': 'control',
    'Discipline': 'discipline',
    'Comment': 'comment'
}
LAUNCH_NATO_RENAME = {
    'Russia': 'Russia',
    'United States': 'United States',
    'China': 'China',
    'France': 'NATO Ally',
    'Japan': 'Other',
    'India': 'Major Non-NATO Ally',
    'New Zealand': 'Other',
    'ESA': 'NATO Ally',
    'Israel': 'NATO Ally',
    'Italy': 'NATO Ally',
    'Iran': 'Other',
    'South Korea': 'Major Non-NATO Ally',
    'Cayman Islands': 'Other',
    'North Korea': 'Major Non-NATO Ally',
    'United Kingdom': 'NATO Ally'
}
LAUNCH_ORG_RENAME = {
    'US': 'United States', 'CN': 'China', 'J': 'Japan', 'RU': 'Russia', 'UK': 'United Kingdom', 'SU': 'Russia',
    'F': 'France', 'D': 'Germany', 'CA': 'Canada', 'IN': 'India', 'I': 'Italy', 'E': 'Spain', 'AU': 'Australia',
    'KR': 'South Korea', 'NL': 'Netherlands', 'BR': 'Brazil', 'S': 'Sweden', 'AR': 'Argentina', 'IL': 'Israel',
    'TR': 'Turkey', 'N': 'Norway', 'UAE': 'United Arab Emirates', 'DR': 'Dominican Republic', 'ID': 'Indonesia',
    'SG': 'Singapore', 'DK': 'Denmark', 'B': 'Belgium', 'CZ': 'Czech Republic', 'CH': 'Switzerland', 'TW': 'Taiwan',
    'MX': 'Mexico', 'PL': 'Poland', 'IR': 'Iran', 'T': 'Thailand', 'L': 'Luxembourg', 'PK': 'Pakistan', 'MY': 'Malaysia',
    'ZA': 'South Africa', 'UA': 'Ukraine', 'AT': 'Austria', 'KP': 'North Korea', 'IQ': 'Iraq', 'HK': 'Hong Kong',
    'EG': 'Egypt', 'GR': 'Greece', 'NZ': 'New Zealand', 'P': 'Portugal', 'FI': 'Finland', 'DD': 'East Germany',
    'HU': 'Hungary', 'I-EU': 'European Union', 'PH': 'Philippines', 'VN': 'Vietnam', 'SA': 'Saudi Arabia', 'BY': 'Belarus',
    'SK': 'Slovakia', 'I-NATO': 'NATO', 'KZ': 'Kazakhstan', 'LT': 'Lithuania', 'BM': 'Bermuda', 'BGN': 'Bulgaria',
    'PE': 'Peru', 'RO': 'Romania', 'BG': 'Bulgaria', 'CL': 'Chile', 'LK': 'Sri Lanka', 'AM': 'Armenia', 'MC': 'Monaco',
    'KE': 'Kenya', 'MN': 'Mongolia', 'BD': 'Bangladesh', 'IE': 'Ireland', 'MU': 'Mauritius', 'UY': 'Uruguay', 'EE': 'Estonia',
    'CO': 'Colombia', 'NG': 'Nigeria', 'CYM': 'Cayman Islands', 'SY': 'Syria', 'EC': 'Ecuador', 'LA': 'Laos', 'AF': 'Afghanistan',
    'DZ': 'Algeria', 'KW': 'Kuwait', 'RW': 'Rwanda', 'YE': 'Yemen', 'KORS': 'South Korea', 'MA': 'Morocco', 'SI': 'Slovenia',
    'NP': 'Nepal', 'GE': 'Georgia', 'I-ESA': 'ESA', 'AZ': 'Azerbaijan', 'QA': 'Qatar', 'CR': 'Costa Rica', 'OM': 'Oman',
    'TM': 'Turkmenistan', 'PR': 'Puerto Rico', 'ZR': 'Zaire', 'MOCN': 'Macau', 'MD': 'Moldova', 'PG': 'Papua New Guinea',
    'SN': 'Senegal', 'PY': 'Paraguay', 'LV': 'Latvia', 'MYM': 'Myanmar', 'I-ELDO': 'ELDO', 'LB': 'Lebanon', 'I-ARAB': 'Arab League',
    'X': 'International', 'ZW': 'Zimbabwe', 'AO': 'Angola', 'VE': 'Venezuela', 'VA': 'Vatican City', 'BO': 'Bolivia', 'BT': 'Bhutan',
    'BVI': 'British Virgin Islands', 'CU': 'Cuba', 'DJ': 'Djibouti', 'UG': 'Uganda', 'ET': 'Ethiopia', 'GH': 'Ghana', 'KH': 'Cambodia',
    'GT': 'Guatemala', 'SD': 'Sudan', 'IS': 'Iceland', 'TN': 'Tunisia', 'I-ESRO': 'ESRO', 'I-EUM': 'EUMETSAT', 'KG': 'Kyrgyzstan',
    'I-EUT': 'EUTELSAT', 'I-INM': 'INMARSAT', 'JO': 'Jordan', 'TO': 'Tonga', 'I-INT': 'INTELSAT', 'TC': 'Turks and Caicos Islands',
    'TF': 'French Southern and Antarctic Lands', 'TTPI': 'Trust Territory of the Pacific Islands', 'TJ': 'Tajikistan', 'UZ': 'Uzbekistan',
    'UM79': 'United States Minor Outlying Islands', 'SH': 'Saint Helena', 'UM67': 'United States Minor Outlying Islands',
    'SR': 'Suriname', 'EARTH': 'Earth', 'PCZ': 'Panama Canal Zone', 'BB': 'Barbados', 'DML': 'Dronning Maud Land',
    'CM': 'Cameroon', 'CK': 'Cook Islands', 'CI': 'Ivory Coast', 'BS': 'Bahamas', 'BBUK': 'Bishop of Birmingham', 'BAT': 'British Antarctic Territory',
    'GI': 'Gibraltar', 'ARV': 'Arvon', 'AQ': 'Antarctica', 'ANTN': 'Antarctica', 'AGUK': 'Agencies of the United Kingdom',
    'AG': 'Antigua and Barbuda', 'AAT': 'Australian Antarctic Territory', 'DX': 'Deutschland', 'GL': 'Greenland', 'PAR': 'Paraguay',
    'KI': 'Kiribati', 'NZRD': 'New Zealand', 'NI': 'Nicaragua', 'MV': 'Maldives', 'MR': 'Mauritania', 'MH': 'Marshall Islands',
    'LY': 'Libya', 'LUNA': 'Luna', 'GRD': 'Grenada', 'I-RASC': 'RASC', 'I-ISS': 'ISS', 'I-CSC1': 'CSC', 'I-CSC': 'CSC',
    'GUF': 'French Guiana', 'GU': 'Guam', 'CSSR': 'Czechoslovakia'
}
SAT_CLASS_RENAME = {
    'B': 'Commercial',
    'D': 'Defense',
    'C': 'Civil',
    'A': 'Amateur',
    'CD': 'Civil',
    'BD': 'Commercial',
    'CB': 'Civil',
    'BC': 'Commercial'
}
OBJECT_ID_ORDER_PIECE_LETTER = {
    1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G', 8: 'H', 9: 'J', 10: 'K',
    11: 'L', 12: 'M', 13: 'N', 14: 'P', 15: 'Q', 16: 'R', 17: 'S', 18: 'T', 19: 'U', 20: 'V',
    21: 'W', 22: 'X', 23: 'Y', 24: 'Z', 25: 'AA', 26: 'AB', 27: 'AC', 28: 'AD', 29: 'AE', 30: 'AF',
    31: 'AG', 32: 'AH', 33: 'AJ', 34: 'AK', 35: 'AL', 36: 'AM', 37: 'AN', 38: 'AP', 39: 'AQ', 40: 'AR',
    41: 'AS', 42: 'AT', 43: 'AU', 44: 'AV', 45: 'AW', 46: 'AX', 47: 'AY', 48: 'AZ', 49: 'BA', 50: 'BB',
    51: 'BC', 52: 'BD', 53: 'BE', 54: 'BF', 55: 'BG', 56: 'BH', 57: 'BJ', 58: 'BK', 59: 'BL', 60: 'BM',
    61: 'BN', 62: 'BP', 63: 'BQ', 64: 'BR', 65: 'BS', 66: 'BT', 67: 'BU', 68: 'BV', 69: 'BW', 70: 'BX',
    71: 'BY', 72: 'BZ'
}
PIECE_ID_HARVARD_DESIGNATION_ORDER = {
    1: 'ALP', 2: 'BET', 3: 'GAM', 4: 'DEL', 5: 'EPS', 6: 'ZET', 7: 'ETA', 8: 'THE', 9: 'IOT', 10: 'KAP',
    11: 'LAM', 12: 'MU', 13: 'NU', 14: 'XI', 15: 'OMI', 16: 'PI', 17: 'RHO', 18: 'SIG', 19: 'TAU', 20: 'UPS',
    21: 'PHI', 22: 'CHI', 23: 'PSI', 24: 'OME', 25: 'A ALP', 26: 'A BET', 27: 'A GAM', 28: 'A DEL', 29: 'A EPS', 30: 'A ZET',
    31: 'A ETA', 32: 'A THE', 33: 'A IOT', 34: 'A KAP', 35: 'A LAM', 36: 'A MU', 37: 'A NU', 38: 'A XI', 39: 'A OMI', 40: 'A PI',
    41: 'A RHO', 42: 'A SIG', 43: 'A TAU', 44: 'A UPS', 45: 'A PHI', 46: 'A CHI', 47: 'A PSI', 48: 'A OME', 49: 'B ALP', 50: 'B BET',
    51: 'B GAM', 52: 'B DEL', 53: 'B EPS', 54: 'B ZET', 55: 'B ETA', 56: 'B THE', 57: 'B IOT', 58: 'B KAP', 59: 'B LAM', 60: 'B MU',
    61: 'B NU', 62: 'B XI', 63: 'B OMI', 64: 'B PI', 65: 'B RHO', 66: 'B SIG', 67: 'B TAU', 68: 'B UPS', 69: 'B PHI', 70: 'B CHI',
    71: 'B PSI', 72: 'B OME'
}
ALL_COL_RENAME_DICTS = [
    LAUNCH_COL_NAMES,
    CELESTRAK_SATCAT_COL_NAMES,
    CURRENTCAT_COL_NAMES,
    LAUNCHLOG_COL_NAMES,
    ORGS_COL_NAMES,
    PSATCAT_COL_NAMES,
    SATCAT_COL_NAMES
]
ALL_VAL_RENAME_DICTS = [
    SAT_CLASS_RENAME,
    LAUNCH_ORG_RENAME,
    LAUNCH_NATO_RENAME
]
