LAUNCH_COL_NAMES = {
    '#Launch_Tag': 'launch_ID',
    'Launch_JD': 'Julian_Date',
    'Launch_Date': 'launch_date',
    'LV_Type': 'rocket_type',
    'Variant': 'rocket_variant',
    'Flight_ID': 'flight_ID',
    'Flight': 'payload',
    'Mission': 'mission_name',
    'FlightCode': 'flight_code',
    'Platform': 'launch_platform',
    'Launch_Site': 'launch_site',
    'Launch_Pad': 'launch_pad',
    'Ascent_Site': 'ascent_site',
    'Ascent_Pad': 'ascent_pad',
    'Apogee': 'apogee_(km)',
    'Apoflag': 'apogee_flag',
    'Range': 'range_(km)',
    'RangeFlag': 'range_flag',
    'Dest': 'destination',
    'OrbPay': 'payload_(t)',
    'Agency': 'launch_agency',
    'Launch_Code': 'launch_code',
    'Group': 'leading_org',
    'Category': 'flight_type',
    'LTCite': 'time_reference',
    'Cite': 'additional_ref',
    'Notes': 'notes'
}
CELESTRAK_SATCAT_COL_NAMES = {
    'OBJECT_NAME': 'satellite_name',
    'OBJECT_ID': 'intl_designator',
    'NORAD_CAT_ID': 'norad_id',
    'OBJECT_TYPE': 'object_type',
    'OPS_STATUS_CODE': 'ops_status',
    'OWNER': 'owner',
    'LAUNCH_DATE': 'launch_date',
    'LAUNCH_SITE': 'launch_site',
    'DECAY_DATE': 'decay_date',
    'PERIOD': 'orbital_period',
    'INCLINATION': 'inclination_deg',
    'APOGEE': 'apogee_km',
    'PERIGEE': 'perigee_km',
    'RCS': 'radar_cross_sec',
    'DATA_STATUS_CODE': 'data_status',
    'ORBIT_CENTER': 'orbit_center',
    'ORBIT_TYPE': 'orbit_type'
}
CURRENTCAT_COL_NAMES = {
    '#JCAT': 'JCAT_number',
    'DeepCat': 'DeepSpace_cat',
    'Satcat': 'Sat_catalog',
    'Piece': 'piece_ID',
    'Active': 'active_status',
    'Type': 'object_type',
    'Name': 'object_name',
    'LDate': 'launch_date',
    'Parent': 'parent_object',
    'Owner': 'object_owner',
    'State': 'object_state',
    'SDate': 'status_date',
    'ExpandedStatus': 'exp_status',
    'DDate': 'phase_end_date',
    'ODate': 'orbit_date',
    'Period': 'orbital_period',
    'Perigee': 'perigee_km',
    'PF': 'perigee_flag',
    'Apogee': 'apogee_km',
    'AF': 'apogee_flag',
    'Inc': 'inclination',
    'IF': 'incl_flag',
    'OpOrbit': 'oper_orbit'
}
LAUNCHLOG_COL_NAMES = {
    '#Launch_Tag': 'launch_ID',
    'Launch_Date': 'launch_date',
    'Piece': 'piece_ID',
    'Type': 'object_type',
    'Name': 'object_name',
    'PLName': 'payload_name',
    'JCAT': 'JCAT_number',
    'SatOwner': 'sat_owner',
    'SatState': 'sat_state',
    'LV_Type': 'rocket_type',
    'Flight_ID': 'flight_ID',
    'Platform': 'launch_platform',
    'Launch_Site': 'launch_site',
    'Launch_Pad': 'launch_pad',
    'Ascent_Site': 'ascent_site',
    'Ascent_Pad': 'ascent_pad',
    'Agency': 'launch_agency',
    'LVState': 'LV_state',
    'Launch_Code': 'launch_code',
    'LTCite': 'time_ref'
}
ORGS_COL_NAMES = {
    '#Code': 'org_code',
    'UCode': 'UN_code',
    'StateCode': 'state_code',
    'Type': 'org_type',
    'Class': 'org_class',
    'TStart': 'start_time',
    'TStop': 'stop_time',
    'ShortName': 'short_name',
    'Name': 'org_name',
    'Location': 'org_location',
    'Longitude': 'longitude',
    'Latitude': 'latitude',
    'Error': 'location_error',
    'Parent': 'parent_org',
    'ShortEName': 'short_EN_name',
    'EName': 'EN_name',
    'UName': 'UN_name'
}
PSATCAT_COL_NAMES = {
    '#JCAT': 'JCAT_number',
    'Piece': 'piece_ID',
    'Name': 'object_name',
    'LDate': 'launch_date',
    'TLast': 'last_time',
    'TOp': 'oper_time',
    'TDate': 'date',
    'TF': 'time_flag',
    'Program': 'program',
    'Plane': 'plane',
    'Att': 'attitude',
    'Mvr': 'maneuver',
    'Class': 'class',
    'Category': 'category',
    'UNState': 'UN_state',
    'UNReg': 'UN_reg',
    'UNPeriod': 'UN_period',
    'UNPerigee': 'UN_perigee',
    'UNApogee': 'UN_apogee',
    'UNInc': 'UN_incl',
    'Result': 'result',
    'Control': 'control',
    'Discipline': 'discipline',
    'Comment': 'comment'
}
LAUNCH_NATO_RENAME = {
    "Russia": "Russia",
    "United States": "United States",
    "China": "China",
    "France": "NATO Ally",
    "Japan": "Other",
    "India": "Major Non-NATO Ally",
    "New Zealand": "Other",
    "ESA": "NATO Ally",
    "Israel": "NATO Ally",
    "Italy": "NATO Ally",
    "Iran": "Other",
    "South Korea": "Major Non-NATO Ally",
    "Cayman Islands": "Other",
    "North Korea": "Major Non-NATO Ally",
    "United Kingdom": "NATO Ally"
}
LAUNCH_ORG_RENAME = {
    'US': 'United States', 'CN': 'China', 'J': 'Japan', 'RU': 'Russia', 'UK': 'United Kingdom', 'SU': 'Russia',
    'F': 'France', 'D': 'Germany', 'CA': 'Canada', 'IN': 'India', 'I': 'Italy', 'E': 'Spain', 'AU': 'Australia',
    'KR': 'South Korea', 'NL': 'Netherlands', 'BR': 'Brazil', 'S': 'Sweden', 'AR': 'Argentina', 'IL': 'Israel',
    'TR': 'Turkey', 'N': 'Norway', 'UAE': 'United Arab Emirates', 'DR': 'Dominican Republic', 'ID': 'Indonesia',
    'SG': 'Singapore', 'DK': 'Denmark', 'B': 'Belgium', 'CZ': 'Czech Republic', 'CH': 'Switzerland', 'TW': 'Taiwan',
    'MX': 'Mexico', 'PL': 'Poland', 'IR': 'Iran', 'T': 'Thailand', 'L': 'Luxembourg', 'PK': 'Pakistan', 'MY': 'Malaysia',
    'ZA': 'South Africa', 'UA': 'Ukraine', 'AT': 'Austria', 'KP': 'North Korea', 'IQ': 'Iraq', 'HK': 'Hong Kong',
    'EG': 'Egypt', 'GR': 'Greece', 'NZ': 'New Zealand', 'P': 'Portugal', 'FI': 'Finland', 'DD': 'East Germany',
    'HU': 'Hungary', 'I-EU': 'European Union', 'PH': 'Philippines', 'VN': 'Vietnam', 'SA': 'Saudi Arabia', 'BY': 'Belarus',
    'SK': 'Slovakia', 'I-NATO': 'NATO', 'KZ': 'Kazakhstan', 'LT': 'Lithuania', 'BM': 'Bermuda', 'BGN': 'Bulgaria',
    'PE': 'Peru', 'RO': 'Romania', 'BG': 'Bulgaria', 'CL': 'Chile', 'LK': 'Sri Lanka', 'AM': 'Armenia', 'MC': 'Monaco',
    'KE': 'Kenya', 'MN': 'Mongolia', 'BD': 'Bangladesh', 'IE': 'Ireland', 'MU': 'Mauritius', 'UY': 'Uruguay', 'EE': 'Estonia',
    'CO': 'Colombia', 'NG': 'Nigeria', 'CYM': 'Cayman Islands', 'SY': 'Syria', 'EC': 'Ecuador', 'LA': 'Laos', 'AF': 'Afghanistan',
    'DZ': 'Algeria', 'KW': 'Kuwait', 'RW': 'Rwanda', 'YE': 'Yemen', 'KORS': 'South Korea', 'MA': 'Morocco', 'SI': 'Slovenia',
    'NP': 'Nepal', 'GE': 'Georgia', 'I-ESA': 'ESA', 'AZ': 'Azerbaijan', 'QA': 'Qatar', 'CR': 'Costa Rica', 'OM': 'Oman',
    'TM': 'Turkmenistan', 'PR': 'Puerto Rico', 'ZR': 'Zaire', 'MOCN': 'Macau', 'MD': 'Moldova', 'PG': 'Papua New Guinea',
    'SN': 'Senegal', 'PY': 'Paraguay', 'LV': 'Latvia', 'MYM': 'Myanmar', 'I-ELDO': 'ELDO', 'LB': 'Lebanon', 'I-ARAB': 'Arab League',
    'X': 'International', 'ZW': 'Zimbabwe', 'AO': 'Angola', 'VE': 'Venezuela', 'VA': 'Vatican City', 'BO': 'Bolivia', 'BT': 'Bhutan',
    'BVI': 'British Virgin Islands', 'CU': 'Cuba', 'DJ': 'Djibouti', 'UG': 'Uganda', 'ET': 'Ethiopia', 'GH': 'Ghana', 'KH': 'Cambodia',
    'GT': 'Guatemala', 'SD': 'Sudan', 'IS': 'Iceland', 'TN': 'Tunisia', 'I-ESRO': 'ESRO', 'I-EUM': 'EUMETSAT', 'KG': 'Kyrgyzstan',
    'I-EUT': 'EUTELSAT', 'I-INM': 'INMARSAT', 'JO': 'Jordan', 'TO': 'Tonga', 'I-INT': 'INTELSAT', 'TC': 'Turks and Caicos Islands',
    'TF': 'French Southern and Antarctic Lands', 'TTPI': 'Trust Territory of the Pacific Islands', 'TJ': 'Tajikistan', 'UZ': 'Uzbekistan',
    'UM79': 'United States Minor Outlying Islands', 'SH': 'Saint Helena', 'UM67': 'United States Minor Outlying Islands',
    'SR': 'Suriname', 'EARTH': 'Earth', 'PCZ': 'Panama Canal Zone', 'BB': 'Barbados', 'DML': 'Dronning Maud Land',
    'CM': 'Cameroon', 'CK': 'Cook Islands', 'CI': 'Ivory Coast', 'BS': 'Bahamas', 'BBUK': 'Bishop of Birmingham', 'BAT': 'British Antarctic Territory',
    'GI': 'Gibraltar', 'ARV': 'Arvon', 'AQ': 'Antarctica', 'ANTN': 'Antarctica', 'AGUK': 'Agencies of the United Kingdom',
    'AG': 'Antigua and Barbuda', 'AAT': 'Australian Antarctic Territory', 'DX': 'Deutschland', 'GL': 'Greenland', 'PAR': 'Paraguay',
    'KI': 'Kiribati', 'NZRD': 'New Zealand', 'NI': 'Nicaragua', 'MV': 'Maldives', 'MR': 'Mauritania', 'MH': 'Marshall Islands',
    'LY': 'Libya', 'LUNA': 'Luna', 'GRD': 'Grenada', 'I-RASC': 'RASC', 'I-ISS': 'ISS', 'I-CSC1': 'CSC', 'I-CSC': 'CSC',
    'GUF': 'French Guiana', 'GU': 'Guam', 'CSSR': 'Czechoslovakia'
}
ALL_COL_RENAME_DICTS = [LAUNCH_COL_NAMES,
                        CELESTRAK_SATCAT_COL_NAMES, CURRENTCAT_COL_NAMES, LAUNCH_ORG_RENAME, LAUNCH_NATO_RENAME, LAUNCHLOG_COL_NAMES, ORGS_COL_NAMES, PSATCAT_COL_NAMES]
